Add RSS support for Blog entries
adonisjs/adonisjs.com pull request #19
Opened 2024-06-08 06:01 UTC by msurdi

I wanted to subscribe to your blog using an RSS feed reader and noticed there was no feed for the blog.

Here's a quick implementation for adding RSS support.

2024-10-18 18:32 UTC, Julien-R44 commented
Cool thing to have! Thanks for the PR

Looks good to me. @thetutlage any thoughts ?

2024-10-23 06:55 UTC, RomainLanz commented
Hey @msurdi! 👋🏻 

Thanks for this PR.

Since we are dumping the whole article content, the file will probably grow big.

Wouldn't it be better only to display the title and a summary?

2024-10-23 15:30 UTC, msurdi commented
Hi @RomainLanz! Thanks a lot for taking some time to review this.

I think it's nice to have the full article, so that you can read the posts without leaving your news reader. But I agree the size of this can get quickly out of hand.

I've just pushed a commit where I instead limited the number of posts to the latest 20 available. Would that work?

I'm happy to truncate the content if you still think it's necessary and there's no way around that.

Thanks!

2024-10-24 10:12 UTC, thetutlage commented
I think its fine to have all the contents for now, since we don't have many posts. Later we can see if we want to something different once we start to hit any sort of limits

2024-10-24 10:16 UTC, thetutlage commented
We will also have to update the `build:static` command and write the `blog.xml` file on the disk, since the production site is a static output. https://github.com/adonisjs/adonisjs.com/blob/main/commands/build_static.ts

2024-10-24 10:17 UTC, RomainLanz commented
> I think its fine to have all the contents for now, since we don't have many posts.

Agreed.

One question though: do most RSS readers support JavaScript? Since we might have custom components in those articles, they could potentially break in RSS readers if JavaScript isn’t handled.

2024-10-24 10:18 UTC, thetutlage commented
To be honest, I have not used any RSS readers recently. So yeah, we should give a test run once and see what the ideal experience will be

2024-10-24 14:59 UTC, msurdi commented
@thetutlage I've just added the static generation step for the feed.

Let me know if there is anything else I can do here.

Thanks 🙏

2024-10-27 15:20 UTC, RomainLanz requested changes

2024-10-27 15:20 UTC, RomainLanz commented on resources/views/feeds/blog.edge
> +    <title>Adonis Framework Blog</title>
```suggestion
    <title>AdonisJS Framework Blog</title>
```

2024-10-27 15:20 UTC, RomainLanz commented on resources/views/feeds/blog.edge
> +    <description>All the latest Adonis Framework news.</description>
```suggestion
    <description>All the latest AdonisJS Framework news.</description>
```

2024-10-27 15:20 UTC, RomainLanz commented on resources/views/feeds/blog.edge
> +    <title>Adonis Framework Blog</title>
```suggestion
    <title>AdonisJS Framework Blog</title>
```

2024-10-27 19:48 UTC, msurdi commented
All suggested changes applied.

2024-10-27 19:49 UTC, RomainLanz approved these changes
LGTM

2024-10-30 17:08 UTC, merged

2024-10-30 17:08 UTC, RomainLanz commented
Thanks!

2024-10-30 17:53 UTC, RomainLanz commented
It looks like the generated feed has some issues: https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fadonisjs.com%2F

Can you have a look at it? @msurdi

2024-10-30 18:48 UTC, msurdi commented
Sure, I’ll check this over the weekend.

2024-11-01 07:26 UTC, msurdi commented
@RomainLanz just opened https://github.com/adonisjs/adonisjs.com/pull/28 to address these issues.