New Article "What's next in AdonisJS6"
adonisjs/adonisjs.com pull request #2
Opened 2024-01-24 22:36 UTC by Julien-R44

Added more stuff and technical details about new @adonisjs/vite

Maybe we can merge and publish it the Friday 26

Lemme know if looks okay to you

2024-01-29 04:36 UTC, thetutlage requested changes

2024-02-16 06:02 UTC, thetutlage requested changes

2024-02-16 06:02 UTC, thetutlage commented on content/blog_posts/articles/whats-coming-next-adonisjs-6.md
> +- Limiter
Let's add the link to release notes here. Saying "Limiter (Already released)" https://github.com/adonisjs/limiter/releases/tag/v2.1.0

2024-02-16 06:10 UTC, thetutlage requested changes

2024-02-16 06:10 UTC, thetutlage commented on content/blog_posts/articles/whats-coming-next-adonisjs-6.md
> +This summer we worked on [BentoCache](bentocache.dev) - a caching library for Node.js. It is a standalone and can be used with any framework. We are planning to have a first-party integration with Ad
Full domain with `https://bentocache.dev` is needed here.

2024-02-16 06:10 UTC, thetutlage commented on content/blog_posts/articles/whats-coming-next-adonisjs-6.md
> +This summer we worked on [BentoCache](bentocache.dev) - a caching library for Node.js. It is a standalone and can be used with any framework. We are planning to have a first-party integration with Ad
"This summer" should be "Last summer (2023)"

2024-02-16 06:10 UTC, thetutlage commented on content/blog_posts/articles/whats-coming-next-adonisjs-6.md
> +A few weeks ago, we released [Verrou](verrou.dev), an agnostic package for NodeJS that can be used with any framework. The purpose of the package is to provide a simple API for locking (mutexes), als
Http for `verrou.dev`

2024-02-16 10:59 UTC, Julien-R44 commented on content/blog_posts/articles/whats-coming-next-adonisjs-6.md
> +A few weeks ago, we released [Verrou](verrou.dev), an agnostic package for NodeJS that can be used with any framework. The purpose of the package is to provide a simple API for locking (mutexes), als
Thanks !

2024-02-16 18:22 UTC, thetutlage approved these changes

2024-02-16 19:38 UTC, merged